### ISSUE TITLE
python version? waymo-open-dataset-tf-2-1-0==1.2.0?

### ISSUE THREAD

**Issue by qsunyuan** [OpenDriveLab/UniAD#35] opened 2023-06-24 00:49 UTC
我在配置mmdetection3d的时候：

```command
cd ~
git clone https://github.com/open-mmlab/mmdetection3d.git
cd mmdetection3d
git checkout v0.17.1 # Other versions may not be compatible.
python setup.py install
pip install -r requirements.txt  # Install packages for mmdet3d
```

在使用 python setup.py install 命令的时候出现了如下问题：

```
RuntimeError: Python version >= 3.9 required.
```

想问问作者最初的conda create 的python版本应该设置为3.9吗？

**Comment by qsunyuan** [comment] 2023-06-24 02:07
ERROR: Could not find a version that satisfies the requirement waymo-open-dataset-tf-2-1-0==1.2.0 (from versions: none)
ERROR: No matching distribution found for waymo-open-dataset-tf-2-1-0==1.2.0

使用2-5-0或者2-11-0的版本不兼容

**Comment by seasky100** [comment] 2023-06-24 08:19
waymo-open-dataset-tf-2-3-0

**Comment by qsunyuan** [comment] 2023-06-24 08:49
<img width="915" alt="image" src="https://github.com/OpenDriveLab/UniAD/assets/71776283/f0b09f6b-7a9a-4607-aab6-560141c52f52">

**Comment by AromaticJ** [comment] 2023-06-26 02:59
Same error. My be some errors in doc INSTALL.md?
https://github.com/OpenDriveLab/UniAD/blob/main/docs/INSTALL.md

**Comment by qsunyuan** [comment] 2023-06-26 03:26
My try:

### 1. python3.8: 

Install mmdet3d from source code.

```command
cd ~
git clone https://github.com/open-mmlab/mmdetection3d.git
cd mmdetection3d
git checkout v0.17.1 # Other versions may not be compatible.
python setup.py install 
```

```
RuntimeError: Python version >= 3.9 required.
```

### 2. I shift to the python3.9

pip install waymo-open-dataset-tf-2-1-0==1.2.0

https://github.com/open-mmlab/mmdetection3d/blob/f1107977dfd26155fc1f83779ee6535d2468f449/requirements/optional.txt#L2

```
ERROR
```

check this issue, seems to be incompatible:
https://github.com/waymo-research/waymo-open-dataset/issues/48#issuecomment-926391440

### 3. I shift to the python3.6

it's ok to install the waymo-open-dataset-tf-2-1-0, But other incompatibilities arise.

**Comment by YTEP-ZHI** [comment] 2023-06-26 04:22
@qsunyuan @AromaticJ  Sorry for the late response. I'm checking this problem, and will reply to you soon.

**Comment by xibinyue** [comment] 2023-06-26 06:14
same error

**Comment by weitaoO0** [comment] 2023-06-26 08:45
same error

**Comment by YTEP-ZHI** [comment] 2023-06-26 08:56
Hi @ALL. It seems to be caused by the installation of scipy.
Please try the following commands instead of that in the doc:

```
cd mmdetection3d
git checkout v0.17.1
pip install scipy==1.7.3
pip install scikit-image==0.20.0
pip install -v -e .
```
Then install UniAD as in the doc:
```
cd ~
git clone https://github.com/OpenDriveLab/UniAD.git
cd UniAD
pip install -r requirements.txt
```

**Comment by qsunyuan** [comment] 2023-06-26 12:06
Great! Thx for your help. mmdet3d is ok.

Another Error: 

```
cd UniAD
pip install -r requirements.txt
```

<img width="985" alt="image" src="https://github.com/OpenDriveLab/UniAD/assets/71776283/4bff807a-3ebc-4709-b80b-ab25343cb1b9">

It seems that numpy in uniaid should be <1.20.0

https://github.com/OpenDriveLab/UniAD/blob/6325a087fd2d5a11774273d63500687e0e6f2b77/requirements.txt#L4

**Comment by YTEP-ZHI** [comment] 2023-06-26 12:19
@qsunyuan  Just simply ignore this error. numpy==1.20.0 is required for tracking evaluation.

**Comment by YTEP-ZHI** [comment] 2023-06-28 12:22
I'm closing this issue as there's no further conversation, feel free to reopen it if needed @qsunyuan.

**Closed by YTEP-ZHI** 2023-06-28 12:22 UTC
Labels: bug
